In [1]:
import pandas as pd

In [2]:
# create a new dataframe and reasign a columns as ['A', 'B', 'C']
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns = ['A', 'B', 'C'])

In [3]:
## head() function return the first 5 data and tail() is also there. return last 5 item
df.head()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [4]:
## index represent the row by default it starts from 0, 1, 2 and goes on.
df.index

RangeIndex(start=0, stop=3, step=1)

In [5]:
## converting to list to view our index
df.index.tolist()

[0, 1, 2]

In [6]:
## We can reassign the index values.
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns = ['A', 'B', 'C'], index=['x', 'y', 'z'])

In [7]:
df

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [8]:
## return the information about the data
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [9]:
## describe functions return the usefull data like (count, mean, std, min, max etc...)

df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [10]:
## return the shape of the dataframe
df.shape

(3, 3)

In [11]:
## nunique -> number unique, it returns the total number of unique values in each columns
df.nunique()

A    3
B    3
C    3
dtype: int64

In [12]:
## unique() -> returns the list of unique items present in the specific columns
df['A'].unique()

array([1, 4, 7])

## Loading in dataframes from files

In [13]:
## read the data from the .csv file
coffee = pd.read_csv('./warmup-data/coffee.csv')

In [14]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [15]:
## read the data from .parquet file
results = pd.read_parquet('./data/results.parquet')

In [16]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [17]:
## read the data from .xlsx file
olympics_data = pd.read_excel('./data/olympics-data.xlsx')

In [18]:
olympics_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [19]:
## if excel contains the sheets. we can retrive them by specifing the sheet_name = ...
olympics_data_results = pd.read_excel('./data/olympics-data.xlsx', sheet_name = 'results')

In [20]:
olympics_data_results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [21]:
bios = pd.read_csv('./data/bios.csv')

In [22]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [23]:
## Converting dataframe into specific file format
## path, filename.csv for reference check the documentation 
### to_csv()
### to_parquet()
### to_excel()

## Accessing data with pandas

In [25]:
## display function
display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [29]:
## Access the random data from the dataframe itself
## Every time you run the shell. it should provide the random 10 datas from the coffee Dataframe.
coffee.sample(10)

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
11   Saturday       Latte          35
1      Monday       Latte          15
12     Sunday    Espresso          45
13     Sunday       Latte          35
8      Friday    Espresso          45
6    Thursday    Espresso          40
0      Monday    Espresso          25
2     Tuesday    Espresso          30
5   Wednesday       Latte          25

### loc and iloc
#### loc[#Rows, #Columns]

In [33]:
coffee.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [34]:
coffee.loc[[0, 1, 2]]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

In [35]:
## accessing using slicing operator
coffee.loc[5:12]

          Day Coffee Type  Units Sold
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45

In [36]:
## Row    -> 5:8
## Colums -> ['Day', 'Units Sold']
coffee.loc[5:8, ['Day', 'Units Sold']]

         Day  Units Sold
5  Wednesday          25
6   Thursday          40
7   Thursday          30
8     Friday          45

### iloc -> Almost the same - notice with iloc the upper index is not inclusive where with .loc it was inclusive
#### upper index or column names -> we can represent by numbers. starts from 0, 1 ...
#### iloc[#row, #column]
#### Accessing throw an index

In [41]:
coffee.iloc[5:11, [0,2]]

          Day  Units Sold
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45

In [43]:
## changing the index by coffee day
coffee.index = coffee.Day
# (or)
# coffee.index = coffee['Day']

In [44]:
coffee.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35

In [45]:
coffee.loc[0: 5]

TypeError: cannot do slice indexing on Index with these indexers [0] of type int

In [46]:
coffee.loc['Monday']

           Day Coffee Type  Units Sold
Day
Monday  Monday    Espresso          25
Monday  Monday       Latte          15

In [48]:
coffee.loc['Monday' : 'Wednesday']

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25

In [49]:
## combine with units sold
coffee.loc['Monday' : 'Wednesday', 'Units Sold']

Day
Monday       25
Monday       15
Tuesday      30
Tuesday      20
Wednesday    35
Wednesday    25
Name: Units Sold, dtype: int64

In [50]:
coffee

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25
Thursday    Thursday    Espresso          40
Thursday    Thursday       Latte          30
Friday        Friday    Espresso          45
Friday        Friday       Latte          35
Saturday    Saturday    Espresso          45
Saturday    Saturday       Latte          35
Sunday        Sunday    Espresso          45
Sunday        Sunday       Latte          35

In [51]:
## reseting the default index
coffee.reset_index(drop=True, inplace=True)

In [52]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [53]:
## set or change a specific in dataframe
coffee.loc[1]

Day            Monday
Coffee Type     Latte
Units Sold         15
Name: 1, dtype: object

In [54]:
## update the Units Sold as 10
coffee.loc[1, 'Units Sold'] = 10

In [55]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [63]:
## at and .iat -> is generally faster than .loc when dealing with a single value
coffee.at[0, 'Coffee Type']

'Espresso'

In [64]:
coffee.iat[4, 0]

'Wednesday'

In [65]:
coffee.iat[4, 1] = 'Latte'

In [66]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday       Latte          35

In [67]:
coffee.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

## *Better go with square brackers [ ]-> ["Units Sold"] More robust*

In [70]:
coffee.Units_Sold

AttributeError: 'DataFrame' object has no attribute 'Units_Sold'

In [71]:
## sorting 
coffee.sort_values('Units Sold') # Increasing order

          Day Coffee Type  Units Sold
1      Monday       Latte          10
3     Tuesday       Latte          20
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          30
7    Thursday       Latte          30
4   Wednesday       Latte          35
9      Friday       Latte          35
13     Sunday       Latte          35
11   Saturday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [72]:
coffee.sort_values('Units Sold', ascending=False) # decreasing order

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
9      Friday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          10

In [73]:
coffee.sort_values(['Units Sold', 'Coffee Type'], ascending=[0,1]) # not recommended

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday       Latte          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          10

In [76]:
## Iterations in dataframe
for index, row in coffee.iterrows():
    print(index)
    print(row)
    print('\n')

0
Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object


1
Day            Monday
Coffee Type     Latte
Units Sold         10
Name: 1, dtype: object


2
Day             Tuesday
Coffee Type    Espresso
Units Sold           30
Name: 2, dtype: object


3
Day            Tuesday
Coffee Type      Latte
Units Sold          20
Name: 3, dtype: object


4
Day            Wednesday
Coffee Type        Latte
Units Sold            35
Name: 4, dtype: object


5
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object


6
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object


7
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object


8
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object


9
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object


10
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object


11
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object


12
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object


13
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object